server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/smart-wardrobe

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/users/**

            - id: wardrobe-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/wardrobe/**

            - id: recommendation-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/recommendation/**

            - id: ai-detection-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/ai/**
              filters:
                - StripPrefix=3

            - id: storage-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/storage/**