server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

spring:
  kafka:
    bootstrap-servers: localhost:9092

    admin:
      fail-fast: false

    properties:
      request.timeout.ms: 3000
      default.api.timeout.ms: 3000
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/smart-wardrobe

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000
            response-timeout: 3s
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/users/**

            - id: wardrobe-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/wardrobe/**

            - id: recommendation-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/recommendation/**

            - id: ai-detection-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/ai/**
              filters:
                - StripPrefix=3

            - id: storage-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/storage/**

system-monitoring:
  services:
    - name: User Service
      service-id: user-service
      url: http://localhost:8081/api/v1/users/actuator/health

    - name: Wardrobe Service
      service-id: wardrobe-service
      url: http://localhost:8082/api/v1/wardrobe/actuator/health

    - name: Recommendation Service
      service-id: recommendation-service
      url: http://localhost:8083/api/v1/recommendation/actuator/health

    - name: AI Detection Service
      service-id: ai-detection-service
      url: http://localhost:8084/health

    - name: Storage Service
      service-id: storage-service
      url: http://localhost:8085/api/v1/storage/actuator/health