spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: recommendation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/recommendation_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
  servlet:
    context-path: /api/v1/recommendation

app:
  services:
    api-gateway-url: http://localhost:8080