version: '3.8'

services:
  postgres-storage:
    image: postgres:15-alpine
    container_name: postgres-storage
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storage_db
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5433:5432" 
    volumes:
      - postgres_storage_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_storage_data:
